apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ns-80
---
apiVersion: v1
kind: Service
metadata:
  name: twplus-demo
  namespace: nginx-ns-80
  labels:
    app: sample-nginx
spec:
  selector:
    app: sample-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns-80
  labels:
    app: sample-nginx
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: nginx
        image: 512861115106.dkr.ecr.ap-southeast-3.amazonaws.com/twplus:v3
        ports:
        - containerPort: 80
