apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: nginx-ns-80
  name: sample-tgb
spec:
  serviceRef:
    name: twplus-demo
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-3:512861115106:targetgroup/twplus-tg-80/e7a39214d2bb874e
  targetType: ip
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-05542d582650e7e18
      ports:
      - protocol: TCP
