apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: nginx-deployment
          image: 512861115106.dkr.ecr.ap-southeast-3.amazonaws.com/hello_world:v3
          ports:
          - containerPort: 80
