apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-nginx-ecr
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx-deployment
